<?php

namespace UKMNorge\TidBundle\Repository;

/**
 * BaseMonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseMonthRepository extends \Doctrine\ORM\EntityRepository
{
	public function getYearTotal($max_month, $year) {
		#"SELECT SUM(toWork) as to_work, SUM(holidayMinutes) as holidayMinutes 
		#	WHERE `year` = current_year AND `month` =< current_month"
		$qry = $this->createQueryBuilder('bm')
					->andWhere('bm.year = :year')
					->setParameter('year', $year)
					->andWhere('bm.month <= :month')
					->setParameter('month', $max_month)
					->select('SUM(bm.toWork)')
					->addSelect('SUM(bm.holidayMinutes)')
					->getQuery();
					#->getArrayResult();
		#return array($toWork, $holidayMinutes);
		#dump($qry);
		#dump($qry->getScalarResult());
		$res = $qry->getScalarResult();
		return array($res[0][1], $res[0][2]);
	}
}
