<?php

namespace UKMNorge\TidBundle\Repository;

/**
 * HolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends \Doctrine\ORM\EntityRepository
{
	public function getHolidays($year, $month) {
		return $this->findBy(array("year" => $year, "month" => $month));
	}
}
