<?php

namespace UKMNorge\TidBundle\Repository;

use UKMNorge\TidBundle\User;

/**
 * IntervalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervalRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllByUser(User $user) {

	}

	public function findCurrent(User $user) {
		
	}

	public function findLatestByUser(User $user) {

	}

}
