<?php

namespace UKMNorge\TidBundle\Repository;

use UKMNorge\TidBundle\Entity\User;
use UKMNorge\TidBundle\Entity\Month;

/**
 * IntervalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervalRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllByUser(User $user) {

	}

	public function findCurrent(User $user) {
		
	}

	public function findLatestByUser(User $user) {

	}

	public function getAllIntervalsInMonth(Month $month) {
		$ivals = $this->findBy(array('month' => $month)); 
		return $ivals;
	}

	public function getCurrentInterval(User $user) {
		$qry = $this->createQueryBuilder('i')
			->join('i.month', 'm')
			->andWhere('m.user = :user')
			->andWhere('i.stop IS null')
			->setParameter('user', $user->getId())
			->orderBy('i.start', 'DESC')
			->select('i')
			->getQuery();

		#dump($qry);
		return $qry->getOneOrNullResult();
	}
}
