<?php

namespace UKMNorge\TidBundle\Repository;

/**
 * MonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUserMonth($user, $month, $year) {
		return $this->findOneBy(array('user' => $user, 'month' => $month, 'year' => $year));
	}
}
